wallpaper {
    monitor = eDP-1
    path = /home/sp00nes/Pictures/arch-linux_upscaled.png
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/sp00nes/Pictures/arch-linux_upscaled.png
}

wallpaper {
    monitor = HDMI-A-2
    path = /home/sp00nes/Pictures/arch-linux_upscaled.png
}

splash = false
